### ISSUE TITLE
Show DataEditor on single-click or onelect

### ISSUE THREAD

**Issue by gnudle** [nadbm/react-datasheet#251]

**Comment by gnudle** [comment]
😢

**Comment by navidadelpour** [comment]
Hi @gnudle,
You can have a button in your valueViewer to dispatch double click event on it self.
here I've had a valueViewer component and inside of that i've created a dropdown icon with css
on dropdown button click, you can dispatch the double click event with `bubbles: true` on the dropdown element itself.

![image](https://user-images.githubusercontent.com/38534411/110284223-b5942780-7ff6-11eb-9e4f-6b2e08b786b3.png)

```javascript
function ValueViewer({ value }) {

  function onDropdownButtonClick(e) {
    e.target.dispatchEvent(new Event("dblclick", { bubbles: true }));
  }

  return (
    <span className="value-viewer">
      {value}
      <span className="dropdown-icon" onClick={onDropdownButtonClick}></span>
    </span>
  );
}
``` 

```scss
.dropdown-element {
  position: relative;

  .value-viewer .dropdown-icon::after {
    content: "\f0d7";
    font-family: Dropdown;
    font-size: .75em;
    position: absolute;
    top: .7em;
    right: .6em;
    padding: 0 .5rem;
    color: #202833;
  }
}
```
