### ISSUE TITLE
Remove Line Devider for custom design. == how to Borderless design

### ISSUE THREAD

**Issue by softmarshmallow** [nadbm/react-datasheet#77]
I'm creating custom cheet by assinging ValueViewer as show in

> Sheet with custom renderers
Following the [example](https://nadbm.github.io/react-datasheet/)

the thing is that i want to create a borderless, lineless sheet for my custom design.
should i do by overriding css? if then How?

my custom sheet photo -> [https://imgur.com/a/Nyho6](https://imgur.com/a/Nyho6)

**Comment by nadbm** [comment]
I would just rewrite the css to remove the border as you want. 

But if you want to override it quickly , this should work
```css
.sheet-container table.data-grid tr td.cell {
 border: 0 !important;
}
```
